const products=[
{id:1,name:"White Classic Polo",price:400,collection:"classic",img:"https://images.unsplash.com/photo-1625910513413-5fc45e3a0d7b?auto=format&fit=crop&w=900&q=80",desc:"Clean, refined and easy to style."},
{id:2,name:"Oversized Summer Tee",price:350,collection:"summer",img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",desc:"Relaxed fit for everyday summer looks."},
{id:3,name:"Signature Black Tee",price:350,collection:"new",img:"https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=80",desc:"A modern signature piece."},
{id:4,name:"Limited Statement Tee",price:450,collection:"limited",img:"https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80",desc:"Limited availability."}
];
let cart=JSON.parse(localStorage.getItem("cs_cart")||"[]"), currentProduct=null;
const app=document.querySelector("#app");
function money(n){return "EGP "+n}
function card(p){return `<article class="card" onclick="openProduct(${p.id})"><img src="${p.img}" alt="${p.name}"><div class="card-info"><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div></article>`}
function home(){app.innerHTML=`<section class="hero" id="home"><div class="hero-content"><p class="eyebrow">COLOMBIA_STORE</p><h1>Timeless.<br>Modern.<br>Yours.</h1><p>Premium fashion collections designed for a clean, confident everyday style.</p><a class="primary light" href="#collection/new">SHOP NEW COLLECTION</a></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">Explore</p><h2>Collections</h2></div></div><div class="grid">${["new","summer","classic","bestsellers","limited"].map(c=>`<article class="card" onclick="location.hash='collection/${c}'"><img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80"><div class="card-info"><h3>${title(c)}</h3><span>Explore collection →</span></div></article>`).join("")}</div></section><section class="section"><div class="section-head"><h2>Featured</h2><a href="#collection/new">View all →</a></div><div class="grid">${products.map(card).join("")}</div></section>`}
function title(c){return ({new:"New Collection",summer:"Summer Collection",classic:"Classic Collection",bestsellers:"Best Sellers",limited:"Limited Edition"})[c]||c}
function collection(c){let ps=c==="bestsellers"?products:products.filter(p=>p.collection===c);app.innerHTML=`<section class="collection-hero"><p class="eyebrow">COLOMBIA_STORE</p><h1>${title(c)}</h1><p>Timeless Style. Modern Elegance.</p></section><section class="section"><div class="grid">${ps.length?ps.map(card).join(""):"<p>No products added yet.</p>"}</div></section>`}
function track(){app.innerHTML=`<section class="section track"><p class="eyebrow">COLOMBIA_STORE</p><h1>Track Order</h1><p>Enter your order number to check the latest status.</p><input class="input" id="orderNo" placeholder="Order number"><button class="primary" onclick="lookup()">Track Order</button><div class="status" id="status"></div></section>`}
function lookup(){const n=document.querySelector("#orderNo").value.trim();document.querySelector("#status").style.display="block";document.querySelector("#status").innerHTML=n?`<strong>Order ${n}</strong><p>Order status: <b>Preparing</b></p><small>Live courier tracking can be connected later to a shipping provider.</small>`:"Please enter an order number."}
function route(){let h=location.hash.slice(1)||"home";if(h==="home")home();else if(h==="track")track();else if(h.startsWith("collection/"))collection(h.split("/")[1]);else home()}
function openProduct(id){currentProduct=products.find(p=>p.id===id);document.querySelector("#modalImg").src=currentProduct.img;document.querySelector("#modalName").textContent=currentProduct.name;document.querySelector("#modalPrice").textContent=money(currentProduct.price);document.querySelector("#modalCollection").textContent=title(currentProduct.collection);document.querySelector("#modalDesc").textContent=currentProduct.desc;document.querySelector("#productModal").classList.add("show")}
function updateCart(){document.querySelector("#cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0);document.querySelector("#cartItems").innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><img src="${x.img}"><div><b>${x.name}</b><div>Size: ${x.size}</div><div>${money(x.price)} × ${x.qty}</div></div></div>`).join(""):"<p>Your cart is empty.</p>";document.querySelector("#cartTotal").textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));localStorage.setItem("cs_cart",JSON.stringify(cart))}
document.querySelector("#menuBtn").onclick=()=>{document.querySelector("#drawer").classList.add("open");document.querySelector("#shade").classList.add("open")};document.querySelector("#closeDrawer").onclick=()=>{document.querySelector("#drawer").classList.remove("open");document.querySelector("#shade").classList.remove("open")};document.querySelector("#shade").onclick=document.querySelector("#closeDrawer").onclick;document.querySelector("#closeModal").onclick=()=>document.querySelector("#productModal").classList.remove("show");document.querySelector("#cartBtn").onclick=()=>{updateCart();document.querySelector("#cartPanel").classList.add("show")};document.querySelector("#closeCart").onclick=()=>document.querySelector("#cartPanel").classList.remove("show");document.querySelector("#addBtn").onclick=()=>{let s=document.querySelector("#modalSize").value;let x=cart.find(i=>i.id===currentProduct.id&&i.size===s);if(x)x.qty++;else cart.push({...currentProduct,size:s,qty:1});updateCart();document.querySelector("#productModal").classList.remove("show");document.querySelector("#cartPanel").classList.add("show")};document.querySelector("#checkoutBtn").onclick=()=>alert("Checkout is ready for the next step: customer details + Cash on Delivery.");window.addEventListener("hashchange",route);route();updateCart();